### ISSUE TITLE
Vercel seems to be broken

### ISSUE THREAD

**Issue by Clebal** [CartoDB/carto-react-template#166]
In my last PR #165 Vercel seems to be broken.

I've run `yarn build` in my computer, but it seems to be ok.
![image](https://user-images.githubusercontent.com/9151432/105478189-2976ac80-5ca3-11eb-9e96-f645ec6ccc05.png)

**Comment by VictorVelarde** [comment]
Working now. Sometimes we had gone beyond free limits
