### ISSUE TITLE
Performance issues for SQL-based source, following tutorial

### ISSUE THREAD

**Issue by allthesignals** [CartoDB/carto-react-template#200]
Hi there,

I followed this tutorial: https://github.com/CartoDB/carto-react-template/blob/master/docs/guides/02_page_layer_widgets.md

But I used my own dataset instead: https://nycplanning-web.carto.com/u/planninglabs/dataset/facdb_v2019_12

When I compare the dataset used in the tutorial (~12k rows), it's not that much smaller than my dataset (~30k rows). They are both point geometries. Yet, the performance difference is drastic: when using my dataset, the app barely functions and ultimately runs out of memory before crashing. When I'm able to, I see tons of warnings about Redux in the console.

Here's my source file (along with the full repo attempt): https://github.com/allthesignals/carto-react-app-test/blob/main/src/data/sources/facilitiesSource.js

Any thoughts on this? I'm not sure what is causing this or what the difference is.

Thanks!

Matt

**Comment by VictorVelarde** [comment]
Sorry for the delay @allthesignals. Which version of the lib were you using, latest beta? 

We're working on improving the performance and new features, and we'll release a new rc version very soon.

**Comment by allthesignals** [comment]
> Sorry for the delay @allthesignals. Which version of the lib were you using, latest beta?
> 
> We're working on improving the performance and new features, and we'll release a new rc version very soon.

I posted the whole repo in the issue thread

**Comment by AdriSolid** [comment]
@allthesignals hey!

I did a little check, thanks for posting your example. The main problem with performance is because the immutable/serializable check for the viewport features management.

Please use our latest version, should be fine.

**Comment by VictorVelarde** [comment]
We released yesterday a 1.0.0-rc1, and we'll release soon a 1.0.0-rc2 with some small fixes
