### ISSUE TITLE
Compilation error: Can't resolve 'gl-matrix/mat3'

### ISSUE THREAD

**Issue by julamb** [CartoDB/carto-react-template#287]
Following the steps in [Getting Started](https://github.com/CartoDB/carto-react-template#getting-started) brings up this compilation error: 
```
./node_modules/@math.gl/core/dist/esm/classes/matrix3.js
Module not found: Can't resolve 'gl-matrix/mat3' in '/Users/julien/workspace/tmp/carto-base-3/node_modules/@math.gl/core/dist/esm/classes'
```

`yarn build` shows a similar error.

I've tried `yarn add gl-matrix-mat3` but the error remains. I have the same issue with the other templates (base-2 and sample-app-2).

**Comment by julamb** [comment]
I was able to work around the issue by adding the following entries to `config.resolve.alias` in `config-overrides.js`, not sure why this is needed though:

```
    "gl-matrix/common": path.resolve('./node_modules/gl-matrix/dist/esm/common.js'),
    "gl-matrix/mat2": path.resolve('./node_modules/gl-matrix/dist/esm/mat2.js'),
    "gl-matrix/mat2d": path.resolve('./node_modules/gl-matrix/dist/esm/mat2d.js'),
    "gl-matrix/mat3": path.resolve('./node_modules/gl-matrix/dist/esm/mat3.js'),
    "gl-matrix/mat4": path.resolve('./node_modules/gl-matrix/dist/esm/mat4.js'),
    "gl-matrix/quat": path.resolve('./node_modules/gl-matrix/dist/esm/quat.js'),
    "gl-matrix/quat2": path.resolve('./node_modules/gl-matrix/dist/esm/quat2.js'),
    "gl-matrix/vec2": path.resolve('./node_modules/gl-matrix/dist/esm/vec2.js'),
    "gl-matrix/vec3": path.resolve('./node_modules/gl-matrix/dist/esm/vec3.js'),
    "gl-matrix/vec4": path.resolve('./node_modules/gl-matrix/dist/esm/vec4.js')
```

**Comment by borja-munoz** [comment]
Hi, the only thing I see different is a new release of the gl-matrix package. Version 3.4.0 was published some hours ago and maybe math.gl needs to be updated as well.

**Comment by borja-munoz** [comment]
As suspected, it is a problem related to gl-matrix. Please take a look at this [issue](https://github.com/uber-web/math.gl/issues/252) in the math.gl project.
